# Generated by Django 4.1.5 on 2023-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='mountain.jpg', upload_to='profile_pics'),
        ),
    ]
